# Generated by Django 2.2 on 2019-04-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_area_text', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
