# Generated by Django 2.2 on 2019-04-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190428_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
