# Generated by Django 2.2 on 2019-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_home_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='banner_area_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
