# Generated by Django 2.2 on 2019-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190428_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
